on: 
  push:
    branches:
      - main

jobs:
  check-directory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Print Current Directory
        run: pwd

      - name: List Directory Contents
        run: ls -la

