name: Nexla GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip3 install nexla-3.2.1-py3-none-any.whl

    - name: Debug Nexla Environment and Token
      run: |
        echo "Environment: ${{ secrets.NEXLA_ENVIRONMENT }}"
        echo "Access Token: ${{ secrets.NEXLA_ACCESS_TOKEN }}"

    - name: Configuring Nexla Environment
      env:
        NEXLA_ENVIRONMENT: ${{ secrets.NEXLA_ENVIRONMENT }}
        NEXLA_ACCESS_TOKEN: ${{ secrets.NEXLA_ACCESS_TOKEN }}
      run: |
        nexla env configure --environment "$NEXLA_ENVIRONMENT" --token "$NEXLA_ACCESS_TOKEN"
